---

name: Publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        env:
          deploy_key: ${{secrets.deploy_key}}
          known_hosts: ${{secrets.known_hosts}}
        run: |
          mkdir -p ${HOME}/.ssh
          printf "%s\n" "$known_hosts" > ${HOME}/.ssh/known_hosts
          printf "%s\n" "$deploy_key" > ${HOME}/.ssh/id_ed25519
          chmod 600 ${HOME}/.ssh/id_ed25519
          eval $(ssh-agent)
          ssh-add
          rsync -a ./ afpy-org@deb.afpy.org:/home/afpy-org/src/
          ssh afpy-org@deb.afpy.org /home/afpy-org/venv/bin/python -m pip install --upgrade setuptools wheel pip
          ssh afpy-org@deb.afpy.org /home/afpy-org/venv/bin/python -m pip install -r /home/afpy-org/src/requirements.txt
          ssh afpy-org@deb.afpy.org /home/afpy-org/venv/bin/python -m pip install sentry-sdk[flask]
          ssh afpy-org@deb.afpy.org sudo systemctl restart afpy-org.service
